version: "3.11"

services:
   redis:
      image: redis:7-alpine
      restart: always
      env_file: .env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:${REDIS_DATA}

   postgres:
      image: postgres:16-alpine
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   bot:
      build: .
      restart: always
      env_file: .env
      depends_on:
         - redis
         - postgres

      # You can remove this field if you don't use webhooks.
      ports:
         - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"

volumes:
   redis-data:
   postgres-data:
