[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "template2"
version = "0.1.0"
description = ""
authors = ["avrtt"]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.4.1"
aiogram_i18n = "^1.3.4"
aiohttp = "^3.9.3"
alembic = "^1.13.1"
asyncpg = "^0.29.0"
redis = "^5.0.3"
sqlalchemy = "^2.0.29"
msgspec = "^0.18.6"
pydantic = "^2.5.3"
pydantic_settings = "^2.1.0"
fluent_runtime = "^0.4.0"

[tool.poetry.group.dev.dependencies]
libcst = "^1.2.0"
black = "^24.4.0"
mypy = "^1.8.0"
ruff = "^0.3.7"

[tool.black]
line-length = 99
exclude = "\\.?venv|\\.cache"

[tool.ruff]
target-version = "py38"
line-length = 99
exclude = [
    ".git",
    ".venv",
    ".idea",
    ".tests",
    ".cache",
    "build",
    "dist",
    "scripts",
]

[tool.ruff.lint]
select = [
    "C",
    "DTZ",
    "E",
    "F",
    "I",
    "ISC",
    "N",
    "PLC",
    "PLE",
    "Q",
    "W",
    "YTT",
    "RET",
    "SIM",
    "ASYNC",
]


[tool.mypy]
plugins = [
    "sqlalchemy.ext.mypy.plugin",
    "pydantic.mypy"
]
exclude = [
    ".git",
    ".venv",
    ".idea",
    ".tests",
    ".cache",
    "build",
    "dist",
    "scripts",
]

[[tool.mypy.overrides]]
module = ["redis.*"]
ignore_missing_imports = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["template2.telegram.handlers.*"]
strict_optional = false
warn_return_any = false
